"""The 23-tab workbook schema (source doc §5, data-model.md).

`SHEET_HEADERS` is the single source of truth for column order per tab,
used by `schema.py` (tab bootstrap) and by every writer/importer that builds
a row dict to append. Column names match data-model.md exactly.
"""

from __future__ import annotations

_COMMON = [
    "record_id",
    "created_at",
    "created_by",
    "updated_at",
    "status",
    "notes",
    "source_id",
    "document_id",
    "evidence_type",
    "confidence",
    "review_status",
    "captured_at",
    "valid_from",
    "valid_to",
    "period_start",
    "period_end",
]

TAB_NAMES = [
    "README",
    "Config",
    "Brands",
    "Operators",
    "Licences",
    "Sources",
    "Documents",
    "Observations",
    "Financials",
    "Traffic",
    "Search Interest",
    "Acquisition",
    "Offers",
    "Products",
    "UX Audits",
    "Brand Audits",
    "Reputation",
    "App Presence",
    "Derived Metrics",
    "Research Queue",
    "Change Log",
    "Data Quality",
    "Summary",
]

SHEET_HEADERS: dict[str, list[str]] = {
    "README": [
        "workbook_version",
        "schema_version",
        "last_ingestion_time",
        "last_human_review_time",
        "target_market",
        "owner",
        "repository_url",
        "runbook_url",
    ],
    "Config": ["list_name", "value", "description"],
    "Brands": _COMMON
    + [
        "brand_name",
        "legal_or_trading_name",
        "operator_id",
        "primary_domain",
        "alternate_domains",
        "launch_date",
        "brand_status",
        "brand_type",
        "primary_market",
        "active_markets",
        "restricted_markets",
        "primary_language",
        "currency_options",
        "mobile_web",
        "native_ios_app",
        "native_android_app",
        "crypto_supported",
        "public_description",
        "research_priority",
        "first_observed_at",
        "last_verified_at",
        "sampling_rationale",
        "previous_names",
        "slogan",
        "social_handles",
        "affiliate_programme_name",
        "customer_support_channels",
    ],
    "Operators": _COMMON
    + [
        "operator_name",
        "former_names",
        "ultimate_parent",
        "ownership_type",
        "listed_exchange",
        "ticker",
        "headquarters_country",
        "company_number",
        "website",
        "investor_relations_url",
        "reporting_currency",
        "financial_year_end",
        "brands_owned",
        "employees_reported",
        "last_verified_at",
    ],
    "Licences": _COMMON
    + [
        "operator_id",
        "brand_id",
        "regulator",
        "jurisdiction",
        "official_licence_number",
        "licence_type",
        "licence_status",
        "effective_date",
        "expiry_date",
        "licensee_legal_name",
        "last_verified_at",
    ],
    "Sources": _COMMON
    + [
        "source_type",
        "publisher",
        "title",
        "url",
        "publication_date",
        "accessed_at",
        "reporting_period_start",
        "reporting_period_end",
        "territory",
        "language",
        "is_primary_source",
        "paywalled",
        "authentication_required",
        "robots_or_terms_note",
        "content_hash",
        "archive_path",
        "citation_text",
        "quality_score",
    ],
    "Documents": _COMMON
    + [
        "filename",
        "mime_type",
        "downloaded_at",
        "content_hash",
        "storage_path",
        "file_size_bytes",
        "page_count",
        "text_extraction_status",
        "ocr_used",
        "parser_name",
        "parser_version",
        "raw_text_path",
        "structured_data_path",
        "ingestion_run_id",
    ],
    "Observations": _COMMON
    + [
        "subject_type",
        "subject_id",
        "metric_id",
        "raw_value",
        "raw_unit",
        "normalised_numeric_value",
        "normalised_text_value",
        "normalised_unit",
        "currency",
        "normalised_currency",
        "fx_rate",
        "fx_rate_date",
        "as_of_date",
        "geography",
        "segment",
        "source_locator",
        "verbatim_excerpt",
        "definition_id",
        "comparability_group",
        "comparability_status",
        "calculation_formula",
        "input_observation_ids",
        "methodology_note",
        "fingerprint",
    ],
    "Financials": _COMMON
    + [
        "operator_id",
        "brand_id",
        "financial_metric",
        "raw_value",
        "raw_currency",
        "normalised_value_gbp",
        "segment",
        "territory",
        "reported_or_derived",
        "page_or_table",
        "comparability_note",
        "allocation_method",
        "allocation_assumptions",
        "allocation_range_low",
        "allocation_range_high",
        "allocation_confidence",
    ],
    "Traffic": _COMMON
    + [
        "brand_id",
        "domain",
        "provider",
        "geography",
        "device_scope",
        "estimated_visits",
        "estimated_unique_visitors",
        "visit_duration_seconds",
        "pages_per_visit",
        "bounce_rate",
        "traffic_share_direct",
        "traffic_share_organic",
        "traffic_share_paid",
        "traffic_share_referral",
        "traffic_share_social",
        "traffic_share_display",
        "top_referral_domains",
        "top_destination_domains",
        "provider_methodology_version",
    ],
    "Search Interest": _COMMON
    + [
        "brand_id",
        "query_text",
        "query_type",
        "platform",
        "geography",
        "category",
        "granularity",
        "interest_index",
        "comparison_set_id",
        "anchor_term",
        "export_file_document_id",
    ],
    "Acquisition": _COMMON
    + [
        "brand_id",
        "geography",
        "channel",
        "traffic_share",
        "spend_reported",
        "spend_estimated",
        "new_customers_reported",
        "new_customers_estimated",
        "cpa_reported",
        "cpa_estimate_low",
        "cpa_estimate_mid",
        "cpa_estimate_high",
        "affiliate_model",
        "affiliate_cpa_offer",
        "affiliate_revenue_share_percent",
        "paid_keyword_cpc_low",
        "paid_keyword_cpc_high",
        "methodology_note",
    ],
    "Offers": _COMMON
    + [
        "brand_id",
        "geography",
        "customer_type",
        "offer_type",
        "headline",
        "description",
        "promo_code",
        "minimum_deposit",
        "maximum_bonus",
        "bonus_percentage",
        "free_spins_count",
        "free_spin_value",
        "wagering_multiplier",
        "wagering_basis",
        "qualifying_games",
        "excluded_games",
        "minimum_odds",
        "maximum_bet_during_wagering",
        "time_limit_days",
        "withdrawal_cap",
        "cashback_percentage",
        "cashback_cap",
        "opt_in_required",
        "terms_url",
        "screenshot_document_id",
        "terms_clarity_score",
    ],
    "Products": _COMMON
    + [
        "brand_id",
        "vertical",
        "game_count_estimated",
        "game_provider_count",
        "named_providers",
        "exclusive_games_count",
        "live_casino_available",
        "jackpots_available",
        "sportsbook_available",
        "bingo_available",
        "poker_available",
        "crash_games_available",
        "demo_play_available",
        "game_search_available",
        "filters_available",
        "favourites_available",
        "recently_played_available",
        "recommendations_available",
    ],
    "UX Audits": _COMMON
    + [
        "brand_id",
        "audit_date",
        "auditor",
        "geography",
        "device_type",
        "viewport",
        "logged_in_state",
        "new_or_returning_visitor",
        "cookie_state",
        "homepage_url",
        "registration_steps",
        "registration_fields",
        "registration_required_fields",
        "kyc_requested_at",
        "deposit_steps",
        "game_discovery_score",
        "game_discovery_score_rationale",
        "search_quality_score",
        "search_quality_score_rationale",
        "navigation_clarity_score",
        "navigation_clarity_score_rationale",
        "promotion_clarity_score",
        "promotion_clarity_score_rationale",
        "trust_signal_score",
        "trust_signal_score_rationale",
        "responsible_gambling_score",
        "responsible_gambling_score_rationale",
        "accessibility_score",
        "accessibility_score_rationale",
        "mobile_usability_score",
        "mobile_usability_score_rationale",
        "visual_clutter_score",
        "visual_clutter_score_rationale",
        "performance_score",
        "performance_score_rationale",
        "overall_ux_score",
        "overall_ux_score_rationale",
        "screen_recording_document_id",
        "screenshot_set_path",
        "rubric_version",
    ],
    "Brand Audits": _COMMON
    + [
        "brand_id",
        "audit_date",
        "auditor",
        "primary_colour",
        "secondary_colours",
        "background_style",
        "typography_style",
        "logo_type",
        "mascot_present",
        "photography_present",
        "illustration_present",
        "animation_intensity",
        "visual_density",
        "tone_of_voice",
        "primary_tagline",
        "primary_proposition",
        "target_audience_hypothesis",
        "premium_score",
        "premium_score_rationale",
        "playful_score",
        "playful_score_rationale",
        "trustworthy_score",
        "trustworthy_score_rationale",
        "traditional_score",
        "traditional_score_rationale",
        "crypto_native_score",
        "crypto_native_score_rationale",
        "sports_led_score",
        "sports_led_score_rationale",
        "bonus_led_score",
        "bonus_led_score_rationale",
        "distinctiveness_score",
        "distinctiveness_score_rationale",
        "coherence_score",
        "coherence_score_rationale",
        "brand_rationale",
        "screenshot_set_path",
        "rubric_version",
    ],
    "Reputation": _COMMON
    + [
        "brand_id",
        "platform",
        "profile_url",
        "score",
        "score_scale_max",
        "review_count",
        "recent_review_window_days",
        "recent_review_count",
        "positive_theme_summary",
        "negative_theme_summary",
        "withdrawal_complaint_share",
        "verification_complaint_share",
        "bonus_complaint_share",
        "support_complaint_share",
        "suspected_review_manipulation",
        "methodology_note",
    ],
    "App Presence": _COMMON
    + [
        "brand_id",
        "platform",
        "store_country",
        "app_name",
        "developer_name",
        "app_id",
        "store_url",
        "category",
        "rating",
        "rating_count",
        "review_count",
        "current_version",
        "last_updated_at",
        "minimum_os",
        "app_size_bytes",
        "in_app_purchases",
        "age_rating",
        "download_estimate",
        "rank",
    ],
    "Derived Metrics": [
        "derived_metric_id",
        "subject_type",
        "subject_id",
        "metric_id",
        "period_start",
        "period_end",
        "value",
        "unit",
        "formula_version",
        "formula",
        "input_observation_ids",
        "assumptions",
        "confidence",
        "comparability_status",
        "calculated_at",
        "calculated_by",
        "review_status",
    ],
    "Research Queue": [
        "task_id",
        "subject_type",
        "subject_id",
        "task_type",
        "priority",
        "requested_metric_ids",
        "suggested_sources",
        "assigned_to",
        "status",
        "attempt_count",
        "last_attempt_at",
        "next_attempt_after",
        "blocking_issue",
        "result_summary",
        "created_at",
        "completed_at",
    ],
    "Change Log": [
        "change_id",
        "timestamp",
        "actor",
        "action",
        "sheet_name",
        "record_id",
        "field_name",
        "old_value",
        "new_value",
        "reason",
        "source_id",
        "ingestion_run_id",
    ],
    "Data Quality": [
        "issue_id",
        "detected_at",
        "severity",
        "issue_type",
        "sheet_name",
        "record_id",
        "field_name",
        "description",
        "suggested_fix",
        "assigned_to",
        "status",
        "resolved_at",
    ],
    "Summary": [
        "brand_id",
        "brand_name",
        "pilot_coverage_status",
        "completeness_by_domain",
        "latest_traffic_estimate",
        "search_interest_trend",
        "latest_operator_revenue",
        "latest_active_customer_figure",
        "revenue_per_active_customer",
        "marketing_pct_revenue",
        "current_welcome_offer",
        "ux_score",
        "brand_positioning_scores",
        "reputation_score",
        "data_confidence_indicator",
        "age_of_latest_observation_days",
        "research_gaps",
        "figure_level_note",
    ],
}
